#!/usr/bin/env bash
# 把仓库根各工具的 README.md 同步到 docs/<tool>.md，作为 Jekyll (just-the-docs) 文档页。
# - 顶部注入 Jekyll front-matter (title / nav_order / description)
# - README 中的相对路径 (./xxx 或 foo/bar) 重写为 GitHub blob 绝对链接
# - 没有 README 的工具会跳过 (npm-offline 暂无 README 时即跳过)

set -euo pipefail

REPO_URL="https://github.com/BerBai/Tools"
BRANCH="main"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DOCS="$ROOT/docs"

sync_one() {
    local tool="$1" order="$2" desc="$3"
    local src="$ROOT/$tool/README.md"
    local out="$DOCS/$tool.md"

    if [ ! -f "$src" ]; then
        echo "  skip $tool (no README at $src)"
        return 0
    fi

    {
        echo "---"
        echo "title: $tool"
        echo "nav_order: $order"
        echo "description: $desc"
        echo "---"
        echo ""
        echo "<!-- Auto-generated by 'make sync-docs'. Edit ${tool}/README.md instead. -->"
        echo ""
        # 链接重写规则:
        #  1) [text](./path)        -> GitHub blob 绝对链接
        #  2) [text](path/to/file)  -> GitHub blob 绝对链接 (排除 http(s)://, mailto:, /abs, #anchor)
        # 第二条用 [a-zA-Z0-9._] 起始 + [^):]* 后续, 自然过滤掉协议前缀和绝对路径
        sed -E \
            -e "s|\]\(\./([^)]+)\)|](${REPO_URL}/blob/${BRANCH}/${tool}/\1)|g" \
            -e "s|\]\(([a-zA-Z0-9._][^):]*/[^)]*)\)|](${REPO_URL}/blob/${BRANCH}/${tool}/\1)|g" \
            "$src"
    } > "$out"
    echo "  ${tool}/README.md -> docs/${tool}.md"
}

echo "Syncing READMEs to docs/..."
sync_one "claude-notify"   1 "Claude Code 任务完成 / 需审批通知 hook"
sync_one "newapi"          2 "anyrouter 本地代理"
sync_one "npm-offline"     3 "npm 离线包打包脚本"
sync_one "wmk"             4 "图片 / PDF 水印工具(vendored from BerBai/WMK, GPL-2.0)"
sync_one "jar-runner"      5 "Linux 上 Java jar 进程生命周期管理(start/stop/status/backup)"
sync_one "jar-docker"      6 "jar / war 一键打 Docker 镜像并运行"
sync_one "mongodb-init"    7 "MongoDB SysV init.d 风格管理脚本"
sync_one "service-monitor" 8 "服务存活监控 + 自愈(tomcat / jar 多实例)"
echo "✓ docs/ synced"
